import json
import multiprocessing
import os
from datetime import datetime
from typing import Collection, Any
import http.client
from implementation import funsearch
from implementation import config
from implementation import sampler
from implementation import evaluator_accelerate
from implementation import evaluator
from implementation import code_manipulation
import bin_packing_utils

import json
import multiprocessing
from typing import Collection, Any
import http.client
from implementation import sampler


def _trim_preface_of_body(sample: str) -> str:
    """Trim the redundant descriptions/symbols/'def' declaration before the function body.
    Please see my comments in sampler.LLM (in sampler.py).
    Since the LLM used in this file is not a pure code completion LLM, this trim function is required.

    -Example sample (function & description generated by LLM):
    -------------------------------------
    This is the optimized function ...
    def priority_v2(...) -> ...:
        return ...
    This function aims to ...
    -------------------------------------
    -This function removes the description above the function's signature, and the function's signature.
    -The indent of the code is preserved.
    -Return of this function:
    -------------------------------------
        return ...
    This function aims to ...
    -------------------------------------
    """
    lines = sample.splitlines()
    func_body_lineno = 0
    find_def_declaration = False
    for lineno, line in enumerate(lines):
        # find the first 'def' statement in the given code
        if line[:3] == 'def':
            func_body_lineno = lineno
            find_def_declaration = True
            break
    if find_def_declaration:
        code = ''
        for line in lines[func_body_lineno + 1:]:
            code += line + '\n'
        return code
    return sample


class LLMAPI(sampler.LLM):
    """Language model that predicts continuation of provided source code.
    """

    def __init__(self, samples_per_prompt: int, trim=True):
        super().__init__(samples_per_prompt)
        additional_prompt = ('You are developing and enhancing a part of a Python Function. Specifically the online bin packing problem.'
                             'The code you are seeing was a version of the Heurisitic Function that helps determine which bin has a higher'
                             ' priority for each incoming item. As a heuristic expert, analyze the code '
                             ' based on the score you are seeing (negative the number of bins used, we consider bins used if there is at least some items inside the bin,' \
                             ' for example a score of -500.0 means that 500 bins are used. -10 means that only 10 bins are used. The bigger the better.)'
                             ' and the average fullness of the bin (for example, the number 0.2 suggests that of all the bins used, only 20% filled.)'
                             ' The goal is to maximize the score (closer to 0) and maximize the average fullness of the bin (closer to 1).'
                             ' A good heuristic should allow maximum average fullness of the bins with minimal usage of number of bins. Your analysis should'
                             ' output the enhanced Python code with no descriptions.')
        # additional_prompt = ('Complete a different and more complex Python function. '
        #                      'Be creative and you can insert multiple if-else and for-loop in the code logic.'
        #                      'Only output the Python code, no descriptions.')
        self._additional_prompt = additional_prompt
        self._trim = trim
        # Create a per-run log file in the same directory as this script.
        # Filename format: YYYYMMDD-HHiiss.txt. Open/appends will be used
        # when writing prompts/responses.
        try:
            base_dir = os.path.dirname(os.path.abspath(__file__))
        except Exception:
            base_dir = os.getcwd()
        timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
        self._log_path = os.path.join(base_dir, f"{timestamp}.txt")

    def draw_samples(self, prompt: str) -> Collection[str]:
        """Returns multiple predicted continuations of `prompt`."""
        return [self._draw_sample(prompt) for _ in range(self._samples_per_prompt)]

    def _draw_sample(self, content: str) -> str:
        prompt = '\n'.join([content, self._additional_prompt])
        while True:
            try:
                conn = http.client.HTTPSConnection(host="", port="")
                payload = json.dumps({
                    # "max_tokens": 2048,
                    "model": "gemma3:12b-it-qat",
                    "stream": False,
                    "prompt": prompt,
                    "think": False,
                    "options": {
                        "temperature": 0.2
                    }
                    # "messages": [
                    #     {
                    #         "role": "user",
                    #         "content": prompt
                    #     }
                    # ]
                })
                headers = {
                    'Content-Type': 'application/json'
                }
                conn.request("POST", "/api/generate", payload, headers)
                res = conn.getresponse()
                data = res.read().decode("utf-8")
                data = json.loads(data)
                # response = data['message']['content']
                response = data['response']
                # trim function
                if self._trim:
                    response = _trim_preface_of_body(response)
                # Append prompt and response to the per-run log file.
                try:
                    with open(self._log_path, 'a', encoding='utf-8') as lf:
                        lf.write('-----\n')
                        lf.write(f'TIMESTAMP: {datetime.now().isoformat()}\n')
                        lf.write('PROMPT:\n')
                        lf.write(prompt + '\n\n')
                        lf.write('RESPONSE:\n')
                        lf.write(response + '\n')
                        lf.write('-----\n\n')
                except Exception:
                    # Logging must not break LLM interaction; ignore failures.
                    pass
                return response
            except Exception:
                continue


class Sandbox(evaluator.Sandbox):
    """Sandbox for executing generated code. Implemented by RZ.

    RZ: Sandbox returns the 'score' of the program and:
    1) avoids the generated code to be harmful (accessing the internet, take up too much RAM).
    2) stops the execution of the code in time (avoid endless loop).
    """

    def __init__(self, verbose=False, numba_accelerate=True):
        """
        Args:
            verbose         : Print evaluate information.
            numba_accelerate: Use numba to accelerate the evaluation. It should be noted that not all numpy functions
                              support numba acceleration, such as np.piecewise().
        """
        self._verbose = verbose
        self._numba_accelerate = numba_accelerate

    def run(
            self,
            program: str,
            function_to_run: str,  # RZ: refers to the name of the function to run (e.g., 'evaluate')
            function_to_evolve: str,  # RZ: accelerate the code by decorating @numba.jit() on function_to_evolve.
            inputs: Any,  # refers to the dataset
            test_input: str,  # refers to the current instance
            timeout_seconds: int,
            **kwargs  # RZ: add this
    ) -> tuple[Any, bool]:
        """Returns `function_to_run(test_input)` and whether execution succeeded.

        RZ: If the generated code (generated by LLM) is executed successfully,
        the output of this function is the score of a given program.
        RZ: PLEASE NOTE THAT this SandBox is only designed for bin-packing problem.
        """
        dataset = inputs[test_input]
        result_queue = multiprocessing.Queue()
        process = multiprocessing.Process(
            target=self._compile_and_run_function,
            args=(program, function_to_run, function_to_evolve, dataset, self._numba_accelerate, result_queue)
        )
        process.start()
        process.join(timeout=timeout_seconds)
        if process.is_alive():
            # if the process is not finished in time, we consider the program illegal
            process.terminate()
            process.join()
            results = None, False
        else:
            if not result_queue.empty():
                results = result_queue.get_nowait()
            else:
                results = None, False

        if self._verbose:
            print(f'================= Evaluated Program =================')
            program_: code_manipulation.Program = code_manipulation.text_to_program(text=program)
            func_to_evolve_: str = kwargs.get('func_to_evolve', 'priority')
            function_: code_manipulation.Function = program_.get_function(func_to_evolve_)
            function_: str = str(function_).strip('\n')
            print(f'{function_}')
            print(f'-----------------------------------------------------')
            print(f'Score: {str(results)}')
            print(f'=====================================================')
            print(f'\n\n')

        return results

    def _compile_and_run_function(self, program, function_to_run, function_to_evolve, dataset, numba_accelerate,
                                  result_queue):
        try:
            # optimize the code (decorate function_to_run with @numba.jit())
            if numba_accelerate:
                program = evaluator_accelerate.add_numba_decorator(
                    program=program,
                    function_to_evolve=function_to_evolve
                )
            # compile the program, and maps the global func/var/class name to its address
            all_globals_namespace = {}
            # execute the program, map func/var/class to global namespace
            exec(program, all_globals_namespace)
            # get the pointer of 'function_to_run'
            function_to_run = all_globals_namespace[function_to_run]
            # return the execution results
            results = function_to_run(dataset)
            # the results must be int or float
            if not isinstance(results, (int, float)):
                result_queue.put((None, False))
                return
            result_queue.put((results, True))
        except:
            # if raise any exception, we assume the execution failed
            result_queue.put((None, False))


specification = r'''
import numpy as np


def get_valid_bin_indices(item: float, bins: np.ndarray) -> np.ndarray:
    """Returns indices of bins in which item can fit."""
    return np.nonzero((bins - item) >= 0)[0]


def online_binpack(
        items: tuple[float, ...], bins: np.ndarray
) -> tuple[list[list[float, ...], ...], np.ndarray]:
    """Performs online binpacking of `items` into `bins`."""
    # Track which items are added to each bin.
    packing = [[] for _ in bins]
    # Add items to bins.
    for item in items:
        # Extract bins that have sufficient space to fit item.
        valid_bin_indices = get_valid_bin_indices(item, bins)
        # Score each bin based on heuristic.
        priorities = priority(item, bins[valid_bin_indices])
        # Add item to bin with highest priority.
        best_bin = valid_bin_indices[np.argmax(priorities)]
        bins[best_bin] -= item
        packing[best_bin].append(item)
    # Remove unused bins from packing.
    packing = [bin_items for bin_items in packing if bin_items]
    return packing, bins

@funsearch.run
# Instances is the different testing dataset inside the specific testing data
def evaluate(instances: dict) -> float:
    """Evaluate heuristic function on a set of online binpacking instances."""
    # List storing number of bins used for each instance.
    num_bins = []

    # List to keep track of average fullness of closed bin for each dataset / instance
    avg_fullness_list = []

    # Perform online binpacking for each instance.
    for name in instances:
        instance = instances[name]
        capacity = instance['capacity']
        items = instance['items']
        # Create num_items bins so there will always be space for all items,
        # regardless of packing order. Array has shape (num_items,).
        bins = np.array([capacity for _ in range(instance['num_items'])])
        # Pack items into bins and return remaining capacity in bins_packed, which
        # has shape (num_items,).
        _, bins_packed = online_binpack(items, bins)
        # If remaining capacity in a bin is equal to initial capacity, then it is
        # unused. Count number of used bins.

        # If the bins aren't at their 100%, count them as used
        # Essentially, if this number is very low and minimized, it is great
        num_bins.append((bins_packed != capacity).sum())

        # Average fullness of the bins inside the instance
        closed_bins = bins_packed[bins_packed < capacity]
        # If there exists such closed bin
        if len(closed_bins) > 0:
            fullness = (capacity - closed_bins) / capacity
            avg_fullness = np.mean(fullness)
            avg_fullness_list.append(avg_fullness)
            
    # Minimize such value so that closer to 0 from a negative number
    # yields a better result
    avg_num_bins = np.mean(num_bins)

    # Takes the average of fullness list (gathered from all instances)
    avg_fullness_overall = np.mean(avg_fullness_list) if avg_fullness_list else 0.0

    print(f"[Evaluator Result] Average Number of bins used: {avg_num_bins}")
    print(f"[Evaluator Result] Average fullness of closed bins: {avg_fullness_overall:.4f}")

    return [-avg_num_bins, avg_fullness_overall]

@funsearch.evolve
def priority(item: float, bins: np.ndarray) -> np.ndarray:
    """Returns priority with which we want to add item to each bin.

    Args:
        item: Size of item to be added to the bin.
        bins: Array of capacities for each bin.

    Return:
        Array of same size as bins with priority score of each bin.
    """
    ratios = item / bins
    log_ratios = np.log(ratios)
    priorities = -log_ratios
    return priorities
'''

# It should be noted that the if __name__ == '__main__' is required.
# Because the inner code uses multiprocess evaluation.
if __name__ == '__main__':
    class_config = config.ClassConfig(llm_class=LLMAPI, sandbox_class=Sandbox)
    config = config.Config(samples_per_prompt=4, evaluate_timeout_seconds=30)

    bin_packing_or3 = {'OR3': bin_packing_utils.datasets['OR3']}
    global_max_sample_num = None  # if it is set to None, funsearch will execute an endless loop
    funsearch.main(
        specification=specification,
        inputs=bin_packing_or3,
        config=config,
        max_sample_nums=global_max_sample_num,
        class_config=class_config,
        log_dir='logs/funsearch_llm_api',
    )
