import multiprocessing
import os
import time
from datetime import datetime
from typing import Collection, Any, Sequence, Type

import requests
from dotenv import load_dotenv

import bin_packing_utils
from implementation import code_manipulation, programs_database
from implementation import config
from implementation import evaluator
from implementation import evaluator_accelerate
from implementation import funsearch
from implementation import sampler
from implementation.programs_database import Prompt

load_dotenv()


def _trim_preface_of_body(sample: str) -> str:
    """Trim the redundant descriptions/symbols/'def' declaration before the function body.
    Please see my comments in sampler.LLM (in sampler.py).
    Since the LLM used in this file is not a pure code completion LLM, this trim function is required.

    -Example sample (function & description generated by LLM):
    -------------------------------------
    This is the optimized function ...
    def priority_v2(...) -> ...:
        return ...
    This function aims to ...
    -------------------------------------
    -This function removes the description above the function's signature, and the function's signature.
    -The indent of the code is preserved.
    -Return of this function:
    -------------------------------------
        return ...
    This function aims to ...
    -------------------------------------
    """
    lines = sample.splitlines()
    func_body_lineno = 0
    find_def_declaration = False
    for lineno, line in enumerate(lines):
        # find the first 'def' statement in the given code
        if line[:3] == 'def':
            func_body_lineno = lineno
            find_def_declaration = True
            break
    if find_def_declaration:
        code = ''
        for line in lines[func_body_lineno + 1:]:
            code += line + '\n'
        return code
    return sample


class Constant:
    ANALYSE_LLM_PROMPT_PREFIX: str = """You are an Artificial Intelligence Heuristic Expert.
    You are tasked to work on improving the following heuristic function for the Online Bin Packing problem.
    This heuristic function will determine how to pack items into bins in an online manner, and your goal is to minimize the number of bins used while maximizing the fullness of the bins.
    The code blocks you are seeing is the previous version of the heuristic function.
    The subsequent supplementary information includes evaluation metrics and preliminary recommendations for online binpacking testing.
    As a heuristic expert, you are expected to analyze the previous version(s) of the heuristic function with the feedbacks
    and do some preliminary work:
    First, analyze the program itself, explore a reasonable explanation for why this version shows such results in the tests, and think deeply about how to improve it.
    Please do not output any other code implementations or your thinking process.
    Please use natural language to output only correct and accurate code modification suggestions that are unrelated to the original problem and only pertain to the code level."""

    PROGRAM_LLM_PROMPT_PREFIX: str = """
    Please improve this code snippet according to the following instructions.
    Do not output anything other than the code itself and the comments within it.
    Strictly output the code of the heuristic function.
    """


class LLMAPI(sampler.LLM):
    """Language model that predicts continuation of provided source code.
    """

    def __init__(self, samples_per_prompt: int, trim=True, type: int = 0):
        super().__init__(samples_per_prompt)
        # Adrian: The additional prompt has been taken away since the ProgramDatabase will deliver
        # the narrative feedback.
        self._additional_prompt = ""
        self._trim = trim
        # type=0 refer to analyse, otherwise, program.
        self._type = type
        # Create a per-run log file in the same directory as this script.
        # Filename format: YYYYMMDD-HHiiss.txt. Open/appends will be used
        # when writing prompts/responses.
        try:
            base_dir = os.path.dirname(os.path.abspath(__file__))
        except Exception:
            base_dir = os.getcwd()
        timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
        self._log_path = os.path.join(base_dir, f"{timestamp}.txt")

    def draw_samples(self, prompt: str) -> Collection[str]:
        """Returns multiple predicted continuations of `prompt`."""
        return [self._draw_sample(prompt) for _ in range(self._samples_per_prompt)]

    def _draw_sample(self, content: str) -> str:
        prompt = '\n'.join([content, self._additional_prompt])
        max_attempts = 3
        for attempt in range(1, max_attempts + 1):
            try:
                url = os.environ.get('PROGRAMMER_LLM_ENDPOINT_HOST' if self._type else 'ANALYST_LLM_ENDPOINT_HOST')
                token = os.environ.get('PROGRAMMER_LLM_API_KEY' if self._type else 'ANALYST_LLM_API_KEY')
                model = os.environ.get(
                    'PROGRAMMER_LLM_ENDPOINT_MODEL' if self._type else 'ANALYST_LLM_ENDPOINT_MODEL')

                payload = {
                    "max_tokens": 4096,
                    "model": model,
                    "reasoning_effort": "low",
                    "messages": [
                        {
                            "role": "user",
                            "content": prompt
                        }
                    ]
                }
                headers = {
                    'Authorization': f'Bearer {token}',
                    'User-Agent': 'Apifox/1.0.0 (https://apifox.com)',
                    'Content-Type': 'application/json'
                }

                resp = requests.post(url, headers=headers, json=payload, timeout=300)
                try:
                    resp.raise_for_status()
                except requests.HTTPError:
                    # Print response body for debugging (e.g., 410 Gone with details)
                    print(f"LLMAPI HTTP {resp.status_code}: {resp.text}")
                    raise
                data = resp.json()
                response = data['choices'][0]['message']['content']
                # trim function
                if self._trim:
                    response = _trim_preface_of_body(response)
                # Append prompt and response to the per-run log file.
                try:
                    with open(self._log_path, 'a', encoding='utf-8') as lf:
                        lf.write('-----\n')
                        lf.write(f'TIMESTAMP: {datetime.now().isoformat()}\n')
                        lf.write('PROMPT:\n')
                        lf.write(prompt + '\n\n')
                        lf.write('RESPONSE:\n')
                        lf.write(response + '\n')
                        lf.write('-----\n\n')
                except Exception:
                    # Logging must not break LLM interaction; ignore failures.
                    pass
                return response
            except Exception as e:
                # Log the real exception and retry after a short pause
                print(f"LLMAPI._draw_sample attempt {attempt} exception: {e}")
                if attempt == max_attempts:
                    # Stop retrying and raise so upstream can handle the failure.
                    raise RuntimeError(f"LLMAPI._draw_sample failed after {max_attempts} attempts") from e
                time.sleep(2)


class ThoughtAugmentedSampler(sampler.Sampler):
    def __init__(self,
                 database: programs_database.ProgramsDatabase,
                 evaluators: Sequence[evaluator.Evaluator],
                 samples_per_prompt: int,
                 max_sample_nums: int | None = None,
                 llm_class: Type[LLMAPI] = LLMAPI):
        super().__init__(database, evaluators, samples_per_prompt, max_sample_nums, llm_class)
        self._analyse_llm = llm_class(samples_per_prompt, trim=False, type=0)
        self._program_llm = llm_class(samples_per_prompt, type=1)

    def sample_from_llm(self, prompt: Prompt) -> tuple[float, Collection[str]]:
        feedback_lines = self._database.get_island_prompt_feedback(prompt.island_id)
        # Keep code template intact while providing textual feedback context.
        prompt_for_analyse_llm = f'{Constant.ANALYSE_LLM_PROMPT_PREFIX}\n\n{prompt.code}\n\n{feedback_lines}'
        reset_time = time.time()
        analysed_samples = self._analyse_llm.draw_samples(prompt_for_analyse_llm)
        analyse_time = time.time() - reset_time
        samples = []
        program_time = 0
        for analysed_sample in analysed_samples:
            if not analysed_sample:
                continue
            prompt_for_program_llm = f'{Constant.PROGRAM_LLM_PROMPT_PREFIX}\n\n{analysed_sample}\n\n{prompt.code}'
            reset_time = time.time()
            sample = self._program_llm.draw_samples(prompt_for_program_llm)
            program_time = program_time + (time.time() - reset_time)
            samples.extend(sample)
        sample_time = (analyse_time + program_time) / self._samples_per_prompt
        return sample_time, samples


class Sandbox(evaluator.Sandbox):
    """Sandbox for executing generated code. Implemented by RZ.

    RZ: Sandbox returns the 'score' of the program and:
    1) avoids the generated code to be harmful (accessing the internet, take up too much RAM).
    2) stops the execution of the code in time (avoid endless loop).
    """

    def __init__(self, verbose=False, numba_accelerate=True):
        """
        Args:
            verbose         : Print evaluate information.
            numba_accelerate: Use numba to accelerate the evaluation. It should be noted that not all numpy functions
                              support numba acceleration, such as np.piecewise().
        """
        self._verbose = verbose
        self._numba_accelerate = numba_accelerate

    def run(
            self,
            program: str,
            function_to_run: str,  # RZ: refers to the name of the function to run (e.g., 'evaluate')
            function_to_evolve: str,  # RZ: accelerate the code by decorating @numba.jit() on function_to_evolve.
            inputs: Any,  # refers to the dataset
            test_input: str,  # refers to the current instance
            timeout_seconds: int,
            **kwargs  # RZ: add this
    ) -> tuple[Any, bool]:
        """Returns `function_to_run(test_input)` and whether execution succeeded.

        RZ: If the generated code (generated by LLM) is executed successfully,
        the output of this function is the score of a given program.
        RZ: PLEASE NOTE THAT this SandBox is only designed for bin-packing problem.
        """
        dataset = inputs[test_input]
        result_queue = multiprocessing.Queue()
        process = multiprocessing.Process(
            target=self._compile_and_run_function,
            args=(program, function_to_run, function_to_evolve, dataset, self._numba_accelerate, result_queue)
        )
        process.start()
        process.join(timeout=timeout_seconds)
        if process.is_alive():
            # if the process is not finished in time, we consider the program illegal
            process.terminate()
            process.join()
            results = None, False
        else:
            if not result_queue.empty():
                results = result_queue.get_nowait()
            else:
                results = None, False

        if self._verbose:
            print(f'================= Evaluated Program =================')
            program_: code_manipulation.Program = code_manipulation.text_to_program(text=program)
            func_to_evolve_: str = kwargs.get('func_to_evolve', 'priority')
            function_: code_manipulation.Function = program_.get_function(func_to_evolve_)
            function_: str = str(function_).strip('\n')
            print(f'{function_}')
            print(f'-----------------------------------------------------')
            print(f'Score: {str(results)}')
            print(f'=====================================================')
            print(f'\n\n')

        return results

    def _compile_and_run_function(self, program, function_to_run, function_to_evolve, dataset, numba_accelerate,
                                  result_queue):
        try:
            # optimize the code (decorate function_to_run with @numba.jit())
            if numba_accelerate:
                program = evaluator_accelerate.add_numba_decorator(
                    program=program,
                    function_to_evolve=function_to_evolve
                )
            # compile the program, and maps the global func/var/class name to its address
            all_globals_namespace = {}
            # execute the program, map func/var/class to global namespace
            exec(program, all_globals_namespace)
            # get the pointer of 'function_to_run'
            function_to_run = all_globals_namespace[function_to_run]
            # return the execution results
            results = function_to_run(dataset)
            # The results can be numeric score or metric dict with a primary score.
            if isinstance(results, dict):
                if 'primary' not in results or not isinstance(results['primary'], (int, float)):
                    result_queue.put((None, False))
                    return
                result_queue.put((results, True))
                return

            if not isinstance(results, (int, float)):
                result_queue.put((None, False))
                return
            result_queue.put((results, True))
        except:
            # if raise any exception, we assume the execution failed
            result_queue.put((None, False))


specification = r'''
import numpy as np


def get_valid_bin_indices(item: float, bins: np.ndarray) -> np.ndarray:
    """Returns indices of bins in which item can fit."""
    return np.nonzero((bins - item) >= 0)[0]


def online_binpack(
        items: tuple[float, ...], bins: np.ndarray
) -> tuple[list[list[float, ...], ...], np.ndarray]:
    """Performs online binpacking of `items` into `bins`."""
    # Track which items are added to each bin.
    packing = [[] for _ in bins]
    # Add items to bins.
    for item in items:
        # Extract bins that have sufficient space to fit item.
        valid_bin_indices = get_valid_bin_indices(item, bins)
        # Score each bin based on heuristic.
        priorities = priority(item, bins[valid_bin_indices])
        # Add item to bin with highest priority.
        best_bin = valid_bin_indices[np.argmax(priorities)]
        bins[best_bin] -= item
        packing[best_bin].append(item)
    # Remove unused bins from packing.
    packing = [bin_items for bin_items in packing if bin_items]
    return packing, bins

@funsearch.run
# Instances is the different testing dataset inside the specific testing data
def evaluate(instances: dict) -> dict:
    
    """
    Adrian:
    - Modified this function to return more information about the evaluation process.
    - Previously, this function only returns the negative average number of bins used across all instances.
    - This score is only evaluated but is not used for the evolution of the Heuristic. LLM does not receive
      any information about how well the heuristic has performed in previous iterations.
    - As such, I have modified this function to give the following information (average score across all instance):
      1) Primary Score (unit: bins): Negative Average Number of Bins used (the original score value)
      2) Average Number of Bins used (unit: bins): The same as 1) but a positive number
      3) Average Fullness of Bins (unit: %): The average fullness of the bins used in percentage.
      4) Average units of Wasted Space (unit: bins): The average remaining capacity of the bins used.
      5) Standard Deviation of Wasted Space (unit: bins): The standard deviation of the remaining capacity of the bins used.
      6) Percentage of Nearly Full Bins (unit: %): The percentage of bins
    """

    """Evaluate heuristic function on a set of online binpacking instances."""
    # List storing number of bins used for each instance.
    num_bins = []

    # List to keep track of average fullness of closed bin for each dataset / instance
    avg_fullness_list = []

    # Wasted space distribution metrics (remaining capacity of used bins)
    avg_wasted_space_list = []   # mean remaining capacity per used bin
    wasted_space_std_list = []   # stdev of remaining capacity across used bins
    pct_nearly_full_list = []    # fraction of used bins with <10% capacity remaining

    # For better undestanding:
    # avg_wasted_space_list = [27, 25, 24]
    # wasteds_space_std_list = [5, 4, 2]
    # pct_nearly_full_list = [0.1, 0.15, 0.2]
    # These three arrays should have the same length, with their index denoting the result of each instance.
    # 1st instance, average wasted space is 27, with standard deviation of 5 and the percentage of nearly full bins is 10%.

    # Perform online binpacking for each instance.
    for name in instances:
        instance = instances[name]
        capacity = instance['capacity']
        items = instance['items']
        # Create num_items bins so there will always be space for all items,
        # regardless of packing order. Array has shape (num_items,).
        bins = np.array([capacity for _ in range(instance['num_items'])])
        # Pack items into bins and return remaining capacity in bins_packed, which
        # has shape (num_items,).
        _, bins_packed = online_binpack(items, bins)
        # If remaining capacity in a bin is equal to initial capacity, then it is
        # unused. Count number of used bins.

        # If the bins aren't at their 100%, count them as used
        # Essentially, if this number is very low and minimized, it is great
        num_bins.append((bins_packed != capacity).sum())

        # used_bins: remaining capacity of each used bin (this is the wasted space per bin)
        used_bins = bins_packed[bins_packed < capacity]
        
        # Better picture: if there is only 5 bins with the following:
        # used_bins = [0, 12, 37, 5, 21] then it means there are 5 bins used where it
        # at least has some items inside. 0 means it is full, 12 means it has 12 units left, etc.
        
        # Given that at least some bins are used
        if len(used_bins) > 0:
        
            # Fullness: fraction of capacity actually filled
            fullness = (capacity - used_bins) / capacity
            # If the capcity for each bin is 100, if a bin has 12 units remaining
            # then (100-12) / 100 = 0.88, so the fullness is 88%.

            # We then append the average fullness of all the used bins
            # in this test instance.
            avg_fullness_list.append(np.mean(fullness))

            # Wasted space distribution: remaining capacity of used bins
            wasted = used_bins.astype(float)

            # Previously we took the mean of the fullness in percentage.
            # Here, we take the mean of the wasted space.
            # Such that we know, on average, how many units is wasted in this instance.
            avg_wasted_space_list.append(np.mean(wasted))

            # Finally, we take the standard deviation of the wasted capacity as an array.
            # This value will tell us how widely spreaded the wasted space is.
            wasted_space_std_list.append(np.std(wasted))

            # In addition, I also wanted to return a value to LLM
            # such that it knows just how close we are, to reaching the goal.
            nearly_full_threshold = 0.10 * capacity
            # For example, if 10 out of 100 bins are at their 90% fullness,
            # then the percentage is 10%.
            pct_nearly_full_list.append(np.mean(wasted < nearly_full_threshold))

    # Minimize such value so that closer to 0 from a negative number
    # yields a better result
    avg_num_bins = np.mean(num_bins)

    # Takes the average of fullness list (gathered from all instances)
    avg_fullness_overall = np.mean(avg_fullness_list) if avg_fullness_list else 0.0

    avg_wasted_space = np.mean(avg_wasted_space_list) if avg_wasted_space_list else 0.0
    wasted_space_std = np.mean(wasted_space_std_list) if wasted_space_std_list else 0.0
    pct_nearly_full = np.mean(pct_nearly_full_list) if pct_nearly_full_list else 0.0

    return {
        'primary': -float(avg_num_bins),
        'avg_bins_used': float(avg_num_bins),
        'avg_fullness': float(avg_fullness_overall),
        'avg_wasted_space': float(avg_wasted_space),
        'wasted_space_std': float(wasted_space_std),
        'pct_nearly_full': float(pct_nearly_full),
    }

@funsearch.evolve
def priority(item: float, bins: np.ndarray) -> np.ndarray:
    """Returns priority with which we want to add item to each bin.

    Args:
        item: Size of item to be added to the bin.
        bins: Array of capacities for each bin.

    Return:
        Array of same size as bins with priority score of each bin.
    """
    ratios = item / bins
    log_ratios = np.log(ratios)
    priorities = -log_ratios
    return priorities
'''

# It should be noted that the if __name__ == '__main__' is required.
# Because the inner code uses multiprocess evaluation.
if __name__ == '__main__':
    class_config = config.ClassConfig(llm_class=LLMAPI, sandbox_class=Sandbox, sampler_class=ThoughtAugmentedSampler)
    config = config.Config(samples_per_prompt=2, evaluate_timeout_seconds=30)

    bin_packing_or3 = {'OR3': bin_packing_utils.datasets['OR3']}
    global_max_sample_num = None  # if it is set to None, funsearch will execute an endless loop
    funsearch.main(
        specification=specification,
        inputs=bin_packing_or3,
        config=config,
        max_sample_nums=global_max_sample_num,
        class_config=class_config,
        log_dir='logs/funsearch_llm_api',
    )
